export const GAME_CONSTANTS = {
  TURN_TIMEOUT_MS: 30_000,
  RECONNECT_TIMEOUT_MS: 60_000,
  MIN_SCORE_TO_GO_STOP_3P: 3,
  MIN_SCORE_TO_GO_STOP_2P: 7,
  ROOM_CODE_LENGTH: 6,
  MAX_GO_COUNT: 9,
  HAND_SIZE_2P: 10,
  HAND_SIZE_3P: 7,
  FIELD_SIZE_2P: 8,
  FIELD_SIZE_3P: 6,
} as const
